import { StyleSheet, Platform } from 'react-native';
import { width, COLOR, height, getPercentageWidth, getPercentageHeight, cardBorderRadius } from '../constants';

const styles = StyleSheet.create({
  screen: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor:'#F7ABFA'
  },
  logoContainer: {
    paddingVertical: getPercentageHeight(30),
  },
  linearGradient: {
    height,
    width,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    resizeMode: 'contain',
    top: 0,
  },
  logo: {
    width: getPercentageWidth(50),
  },
  scrollContainer: {
    flexGrow: 1,
    paddingVertical: getPercentageHeight(10),
    paddingHorizontal: getPercentageWidth(15),
    width,
    height: Platform.OS === 'ios' ? '100%' : getPercentageHeight(100),
  },
  box: {
    backgroundColor: COLOR.white,
    borderRadius: cardBorderRadius,
    width: '100%',
    paddingTop: getPercentageHeight(20),
    paddingBottom: getPercentageHeight(30),
    paddingHorizontal: getPercentageWidth(20),
  },
  title: {
    alignSelf: 'center',
    fontSize: 22,
    fontWeight: '500',
    color: COLOR.BLUE_TEXT,
    paddingBottom: getPercentageHeight(20),
    paddingTop: getPercentageHeight(10),
  },
  tab: {
    borderRadius: cardBorderRadius,
    width: getPercentageWidth(140),
    borderColor: COLOR.DARK_GRAY_TEXT,
    borderWidth: 1,
    height: getPercentageHeight(37),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedTab: {
    borderRadius: cardBorderRadius,
    width: getPercentageWidth(140),
    borderColor: COLOR.BLUE_GREEN,
    borderWidth: 1,
    height: getPercentageHeight(37),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.BLUE_GREEN,
  },
  inputText: {
    color: COLOR.DARK_GRAY_TEXT,
    fontSize: 14,
    marginTop: getPercentageHeight(15),
  },
  inputContainer: {
    shadowColor: COLOR.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderRadius: cardBorderRadius,
    flexDirection: 'row',
    width: '100%',
    borderRadius: cardBorderRadius,
    borderColor: COLOR.LIGHT_GRAY_BORDER,
    borderWidth: 1,
    backgroundColor: COLOR.white,
    alignItems: 'center',
    justifyContent: 'space-around',
    height: getPercentageHeight(50),
    marginTop: getPercentageHeight(7),
    paddingHorizontal: getPercentageWidth(10),
  },
  inputCode: {
    borderRightColor: COLOR.LIGHT_GRAY_BORDER,
    borderRightWidth: 1,
    height: getPercentageHeight(50),
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: getPercentageWidth(15),
    paddingLeft: getPercentageWidth(10),
  },
  inputBox: {
    borderRadius: cardBorderRadius,
    height: getPercentageHeight(50),
    width: '90%',
  },
  buttonStyle: {
    width: '100%',
    marginTop: getPercentageHeight(30),
  },
  solidButtonStyle: {
    marginTop: getPercentageHeight(20),
    borderRadius: cardBorderRadius,
    width: '100%',
    borderColor: COLOR.DARK_GRAY_TEXT,
    borderWidth: 1,
    height: getPercentageHeight(55),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: COLOR.DARK_GRAY_TEXT,
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 16,
  },
  options: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginTop: getPercentageHeight(20),
  },
  skip: {
    alignSelf: 'center',
    color: COLOR.BLUE_TEXT,
    marginTop: getPercentageHeight(20),
  },
  pickerContainer: {
    backgroundColor: COLOR.white,
    position: 'absolute',
    bottom: 0,
  },
  successful: {
    backgroundColor: COLOR.white,
    borderRadius: cardBorderRadius,
    paddingVertical: getPercentageHeight(30),
    paddingHorizontal: getPercentageWidth(20),
    alignItems: 'center',
  },
  changeMessage: {
    color: COLOR.DARK_GRAY_TEXT,
    fontSize: 12,
    marginTop: getPercentageHeight(20),
  },
});

export { styles };
